---
- hosts: local
  become: yes
  vars_files:
    - vars.yml
  # see vars dependencies in comments
  roles:
    # my_user
    - base
    # my_user, my_home_dir, my_conf_dir
    - bash
    # default_distro_codename
    - bravebrowser
    # my_user, my_bin_dir
    - composer
    - copyq
    - dejadup
    # default_distro_codename
    - deluge
    # default_distro_name, default_distro_codename, docker_compose_version
    - docker
    # my_user, my_home_dir, my_conf_dir, git_user, git_email
    - git
    - googlechrome
    # grub_timeout, grub_recordfail_timeout
    - grub
    # my_user, my_bin_dir
    - mybindir
    # my_user, my_conf_dir
    - myconfdir
    # my_user, nodejs_version
    - nodejs
    - opensshserv
    # default_distro_codename
    - oraclejava
    - skype
    # my_user, sublime_config_dir
    - sublimetext
    - teamviewer
    - timedoctor
    - toolbox
    # vagrant_version
    - vagrant
    # default_distro_codename, virtualbox_version
    - virtualbox
    - vlc
    - vsync
