---
- hosts: local
  become: yes
  vars_files:
    - vars.yml
  # see vars dependencies in comments
  roles:
    # my_user
    - base
    # my_user, my_home_dir, my_conf_dir
    - bash
    - copyq
    # default_distro_name, default_distro_codename, docker_compose_version
    - docker
    # my_user, my_home_dir, my_conf_dir, git_user, git_email
    - git
    - googlechrome
    - skype
    # my_user, my_home_dir, sublime_config_dir
    - sublimetext
    - teamviewer
    - toolbox
    - vlc
