---
# SETTABLE VARS

my_user:  # user
git_user:  # git user
git_email:  # git user email

# CHANGABLE VARS

# supported values: ubuntu, "{{ ansible_distribution | lower }}"
default_distro_name: "{{ ansible_distribution | lower }}"
# supported values: trusty, xenial, "{{ ansible_distribution_release | lower }}"
default_distro_codename: "{{ ansible_distribution_release | lower }}"

my_home_dir: "/home/{{ my_user }}"
my_conf_dir: "{{ my_home_dir }}/.{{ my_user }}_conf"
my_bin_dir: "{{ my_home_dir }}/.{{ my_user }}_bin"
docker_compose_version: 1.18.0
sublime_config_dir: "{{ my_home_dir }}/.config/sublime-text-3/Packages/User"
composer_version: 1.5
nvm_version: 0.33.8
nodejs_version: 6.11
virtualbox_version: 5.2
vagrant_version: 2.0.1
