---
- name: add apt signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ default_distro_name }}/gpg"
    state: present

- name: add ppa
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ default_distro_name }} {{ default_distro_codename }} stable"
    filename: docker

- name: update cache
  shell: apt-get update

- name: install docker-ce
  apt: name=docker-ce state=latest force=yes
  notify: start docker

- name: add {{ my_user }} to docker group
  user: name="{{ my_user }}" groups=docker append=yes
  notify: start docker
