---
- block:

  - name: create user custom bashrc
    template:
      src: bashrc.j2
      dest: "{{ _bash_custom_bashrc_path }}"
      mode: 0600

  - name: include custom bashrc to the user bashrc
    lineinfile:
      dest: "{{ my_home_dir }}/.bashrc"
      create: yes
      mode: 0644
      line: "source {{ _bash_custom_bashrc_path }}"

  become: true
  become_user: "{{ my_user }}"
