---
- block:

  - name: add the user custom gitconfig
    template:
      src: gitconfig.j2
      dest: "{{ _git_custom_gitconfig_path }}"
      mode: 0600

  - name: include custom gitconfig to default gitconfig
    blockinfile:
      dest: "{{ my_home_dir }}/.gitconfig"
      create: yes
      block: |
        [include]
          path = "{{ _git_custom_gitconfig_path }}"

  become: true
  become_user: "{{ my_user }}"
