---
- block:

  - name: add user custom bashrc git config
    template:
      src: bashrc.j2
      dest: "{{ _git_custom_bashrc_path }}"
      mode: 0600

  - name: include custom user bashrc to user bashrc
    lineinfile:
      dest: "{{ my_home_dir }}/.bashrc"
      create: yes
      line: "source {{ _git_custom_bashrc_path }}"

  become: true
  become_user: "{{ my_user }}"
